#!/usr/bin/env node
// build:skill — core.mjs (esbuild) + editor-template.gen.html (vite singlefile).
// --core-only: only core bundle. --check: fail if artifacts don't match sources (CI).
import { build } from "esbuild";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
	"..",
);
const args = new Set(process.argv.slice(2));
const coreOnly = args.has("--core-only");
const check = args.has("--check");

const srcDev = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const coreEntry = path.join(srcDev, "core", "src", "index.ts");
const coreOut = path.join(repo, "llmscheme-skill/block_llm_core/core.mjs");
const templateOut = path.join(
	repo,
	"llmscheme-skill/block_llm_core/editor-template.gen.html",
);
const appIndex = path.join(srcDev, "app/index.html");
const viteRoot = path.join(srcDev, "app");
const budgetHtml = 150 * 1024;

const BANNER =
	"// block-llm core bundle — generated by build:skill, DO NOT EDIT\n";
// pi-lens suppresses ast-grep JS rules via an inline `// pi-lens-ignore:` comment
// on the diagnostic line or the line above; the minified <script type=module>
// gets the markers injected right after the tag at build time. All rules the
// minified bundle trips are listed here so per-edit dispatch suppresses them
// without depending on the project rule policy.
const LENS_IGNORE =
	"// pi-lens-ignore: no-inner-html-js,throw-new-error,unchecked-throwing-call,no-console-except-error,no-extra-boolean-cast,nested-ternary,prefer-number-properties,strict-equality,strict-inequality,prefer-string-slice,prefer-dom-node-append,prefer-at\n";

function buildCore() {
	return build({
		entryPoints: [coreEntry],
		bundle: true,
		format: "esm",
		target: "node20",
		platform: "node",
		banner: { js: BANNER },
		outfile: coreOut,
		logLevel: "warning",
	});
}

async function main() {
	await buildCore();
	let html = null;
	if (!coreOnly) {
		if (check) {
			// artifacts must exist and be newer than their sources
			const newer = (src, art) => {
				if (!fs.existsSync(art)) return true;
				return fs.statSync(src).mtimeMs > fs.statSync(art).mtimeMs;
			};
			const coreNewer = newer(coreEntry, coreOut);
			let htmlNewer = false;
			if (fs.existsSync(path.join(viteRoot, "src"))) {
				for (const p of ["index.html", "src/main.js", "src/App.svelte"]) {
					const f = path.join(viteRoot, p);
					if (fs.existsSync(f) && newer(f, templateOut)) {
						htmlNewer = true;
						break;
					}
				}
			}
			if (coreNewer) {
				console.error(
					`FAIL: ${coreOut} older than sources — run npm run build:skill`,
				);
				process.exit(1);
			}
			if (htmlNewer) {
				console.error(
					`FAIL: ${templateOut} older than app sources — run npm run build:skill`,
				);
				process.exit(1);
			}
			const size = fs.existsSync(templateOut) ? fs.statSync(templateOut).size : 0;
			if (fs.existsSync(templateOut) && size > budgetHtml) {
				console.error(
					`FAIL: editor-template.gen.html ${size}B > budget ${budgetHtml}B`,
				);
				process.exit(1);
			}
			console.log("check OK");
			return;
		}
		if (
			fs.existsSync(path.join(viteRoot, "index.html")) &&
			fs.existsSync(path.join(viteRoot, "src/App.svelte"))
		) {
			console.log("building editor via vite...");
			execFileSync(
				"node",
				[path.join(srcDev, "node_modules/vite/bin/vite.js"), "build"],
				{ cwd: viteRoot, stdio: "inherit" },
			);
			html = fs.readFileSync(path.join(viteRoot, "dist/index.html"), "utf8");
			// inject the pi-lens inline-ignore into the minified module script;
			// the bundle spans a few long lines, so the marker goes onto EVERY code
			// line (comment-only lines are valid JS, +~15×230B) — suppressions then
			// survive any reflow of the minifier
			html = html.replace(
				/(<script type="module"[^>]*>)([\s\S]*?)(<\/script>)/,
				(_, open, code, close) =>
					open +
					code
						.split("\n")
						.map((line) => (line.trim() ? `${LENS_IGNORE.trimEnd()}\n${line}` : line))
						.join("\n") +
					close,
			);
			fs.mkdirSync(path.dirname(templateOut), { recursive: true });
			fs.writeFileSync(templateOut, html);
		} else {
			console.log(
				"app/ skeleton absent — skipping editor-template build (core-only fallback)",
			);
		}
	}
	const size = fs.existsSync(templateOut) ? fs.statSync(templateOut).size : 0;
	console.log(`core.mjs: ${fs.statSync(coreOut).size}B`);
	if (fs.existsSync(templateOut))
		console.log(`editor-template.gen.html: ${size}B (budget ${budgetHtml}B)`);
	if (check) {
		console.log("check OK");
		return;
	}
	if (size > budgetHtml) {
		console.error(
			`FAIL: editor-template.gen.html ${size}B > budget ${budgetHtml}B`,
		);
		process.exit(1);
	}
}

await main();
