import fs from "node:fs";
import path from "node:path";
import type { Scheme, Generator, JournalEntry } from "./types.ts";
import { validate, checkRefs } from "./validate.ts";
import { exportMd } from "./exportMd.ts";

export class CasError extends Error {
	constructor(
		public expected: number,
		public actual: number,
	) {
		super(
			`scheme changed on disk (rev ${expected} → ${actual}), re-read with block.mjs get and retry`,
		);
	}
}
export class ValidationError extends Error {
	constructor(public issues: SchemeIssues) {
		super(`validation failed: ${issues.errors.map((e) => e.message).join("; ")}`);
	}
}
export type SchemeIssues = ReturnType<typeof validate>;

export const DIR = ".block_llm";
export const AUTOSAVE_KEEP = 50;
export const BACKUP_KEEP = 20;
export const JOURNAL_MAX = 5000;

export class DataError extends Error {}

export function readRaw(rootAbs: string): Scheme {
	const file = path.join(rootAbs, DIR, "scheme.json");
	let text: string;
	try {
		text = fs.readFileSync(file, "utf8");
	} catch (e) {
		if ((e as NodeJS.ErrnoException).code === "ENOENT")
			throw new DataError(`no scheme at ${file}`);
		throw new DataError(`cannot read ${file}: ${(e as Error).message}`);
	}
	try {
		return JSON.parse(text);
	} catch (e) {
		throw new DataError(`invalid JSON in ${file}: ${(e as Error).message}`);
	}
}

export function dirSizeLimitExceeded(file: string, limit: number): boolean {
	try {
		return fs.statSync(file).size > limit;
	} catch {
		return false;
	}
}

// rotate cache/<sub> keeping newest `keep` entries
function rotate(dir: string, keep: number) {
	let entries: fs.Dirent[] = [];
	try {
		entries = fs
			.readdirSync(dir, { withFileTypes: true })
			.filter((e) => e.isFile());
	} catch {
		return;
	}
	entries.sort((a, b) => b.name.localeCompare(a.name)); // names are ts-prefixed
	for (const e of entries.slice(keep)) {
		try {
			fs.unlinkSync(path.join(dir, e.name));
		} catch {
			/* best effort */
		}
	}
}

function appendJournal(rootAbs: string, entry: JournalEntry) {
	const cache = path.join(rootAbs, DIR, "cache");
	fs.mkdirSync(cache, { recursive: true });
	const journal = path.join(cache, "journal.jsonl");
	fs.appendFileSync(journal, JSON.stringify(entry) + "\n");
	// rotation: cap lines
	try {
		const lines = fs.readFileSync(journal, "utf8").split("\n").filter(Boolean);
		if (lines.length > JOURNAL_MAX) {
			fs.writeFileSync(journal, lines.slice(-JOURNAL_MAX).join("\n") + "\n");
		}
	} catch {
		/* best effort */
	}
}

function backup(rootAbs: string, scheme: Scheme) {
	const backupDir = path.join(rootAbs, DIR, "cache", "backup");
	fs.mkdirSync(backupDir, { recursive: true });
	const stamp = new Date().toISOString().replace(/[:.]/g, "-");
	fs.writeFileSync(
		path.join(backupDir, `rev${scheme.rev}-${stamp}.json`),
		JSON.stringify(scheme, null, 2) + "\n",
	);
	rotate(backupDir, BACKUP_KEEP);
}

function autosave(rootAbs: string, scheme: Scheme, force: boolean) {
	const dir = path.join(rootAbs, DIR, "cache", "autosave");
	fs.mkdirSync(dir, { recursive: true });
	// rate limit: 1 per 30s unless forced
	try {
		const latest = fs.readdirSync(dir).sort().at(-1);
		if (latest && !force) {
			const m = latest.match(/^ts(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})/);
			if (m) {
				const prev = Date.parse(`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`);
				if (Date.now() - prev < 30_000) return;
			}
		}
	} catch {
		/* empty dir */
	}
	const stamp = new Date().toISOString().replace(/[:.]/g, "-");
	fs.writeFileSync(
		path.join(dir, `ts${stamp}-rev${scheme.rev}.json`),
		JSON.stringify(scheme, null, 2) + "\n",
	);
	rotate(dir, AUTOSAVE_KEEP);
}

export interface SaveOptions {
	// computed AFTER rev bump so exports always match the written revision (§4.3).
	// SCHEME.md is generated by the core itself; extraFiles carries scheme.html etc.
	extraFiles?: (s: Scheme) => Record<string, string>;
	journal?: { actor: Generator; op: string; summary: string };
	autosaveForce?: boolean;
}

// §4.3/§9: single write path. Atomic (tmp+rename), rev+1, CAS, backup, journal,
// then regenerates SCHEME.md (export always follows write).
export function saveSchema(
	rootAbs: string,
	next: Scheme,
	opts: SaveOptions = {},
): { rev: number } {
	const file = path.join(rootAbs, DIR, "scheme.json");
	let current: Scheme | undefined;
	try {
		current = readRaw(rootAbs);
	} catch {
		/* init case: no file yet */
	}
	if (current && current.rev !== next.rev)
		throw new CasError(next.rev, current.rev);

	// validation gate: errors forbid the write
	const issues = validate(next);
	if (issues.errors.length) throw new ValidationError(issues);

	next.rev = (current?.rev ?? next.rev) + 1;
	next.meta.updatedAt = new Date().toISOString();
	const blockDir = path.join(rootAbs, DIR);
	fs.mkdirSync(path.join(blockDir, "cache"), { recursive: true });

	// pre-write backup of the CURRENT state
	if (current) backup(rootAbs, current);
	autosave(rootAbs, next, opts.autosaveForce ?? true);

	// atomic write: tmp + rename in the same directory
	const tmp = path.join(blockDir, `.scheme.json.tmp-${process.pid}`);
	fs.writeFileSync(tmp, JSON.stringify(next, null, 2) + "\n");
	fs.renameSync(tmp, file);

	// regenerated exports (§4.3) — computed AFTER the rev bump, so exports match
	const extraFiles = opts.extraFiles?.(next) ?? {};
	// SCHEME.md is the core's own export — every write regenerates it
	const md = exportMd(next, issues);
	const mdTmp = path.join(rootAbs, "SCHEME.md.tmp-") + process.pid;
	fs.writeFileSync(mdTmp, md);
	fs.renameSync(mdTmp, path.join(rootAbs, "SCHEME.md"));
	for (const [name, content] of Object.entries(extraFiles)) {
		const target = path.join(rootAbs, name);
		const tmp2 = target + `.tmp-${process.pid}`;
		fs.writeFileSync(tmp2, content);
		fs.renameSync(tmp2, target);
	}

	if (opts.journal) {
		appendJournal(rootAbs, {
			ts: new Date().toISOString(),
			actor: opts.journal.actor,
			op: opts.journal.op,
			rev: next.rev,
			summary: opts.journal.summary,
		});
	}
	return { rev: next.rev };
}

export { appendJournal, rotate, validate, checkRefs, exportMd };
