// block-llm core bundle — generated by build:skill, DO NOT EDIT


// core/src/types.ts
var FORMAT = "block-llm";
var SUPPORTED_VERSION = 1;
var SHAPES = [
  "circle",
  "diamond",
  "square",
  "rect",
  "table"
];
var EDGE_STYLES = ["solid", "dashed"];
var MAX_TABLE_COLS = 10;
var MAX_TABLE_ROWS = 50;
var SIDES = ["top", "bottom", "left", "right"];

// core/src/validate.ts
function validate(s) {
  const errors = [];
  const warnings = [];
  const err = (code, message, id) => errors.push({ level: "error", code, message, id });
  const warn = (code, message, id) => warnings.push({ level: "warn", code, message, id });
  if (s.format !== "block-llm")
    err("format", `format must be "block-llm", got ${JSON.stringify(s.format)}`);
  if (!Number.isInteger(s.version) || s.version < 1)
    err("version", `bad version ${JSON.stringify(s.version)}`);
  else if (s.version > SUPPORTED_VERSION)
    err(
      "version",
      `scheme version ${s.version} > supported ${SUPPORTED_VERSION}, update the skill`
    );
  if (!Number.isInteger(s.rev) || s.rev < 0)
    err("rev", `bad rev ${JSON.stringify(s.rev)}`);
  if (!s.name || typeof s.name !== "string") err("name", "name is required");
  const seen = /* @__PURE__ */ new Set();
  for (const n of s.nodes ?? []) {
    if (typeof n.id !== "string" || !n.id) {
      err("id", "node without id");
      continue;
    }
    if (seen.has(n.id)) err("dup-id", `duplicate id ${n.id}`, n.id);
    seen.add(n.id);
    if (!SHAPES.includes(n.shape))
      err("shape", `node ${n.id}: unknown shape ${JSON.stringify(n.shape)}`, n.id);
    if (typeof n.label !== "string" || !n.label.trim())
      warn("label", `node ${n.id}: empty label`, n.id);
    if (n.description !== void 0 && typeof n.description !== "string")
      err("desc", `node ${n.id}: description must be a string`, n.id);
    if (!Number.isFinite(n.x) || !Number.isFinite(n.y))
      err("coords", `node ${n.id}: x/y must be numbers`, n.id);
    if (n.w !== void 0 && (!Number.isFinite(n.w) || n.w < 20))
      err("size", `node ${n.id}: w must be a number \u2265 20`, n.id);
    if (n.h !== void 0 && (!Number.isFinite(n.h) || n.h < 20))
      err("size", `node ${n.id}: h must be a number \u2265 20`, n.id);
    if (n.refs !== void 0) {
      if (!Array.isArray(n.refs) || n.refs.some((r) => typeof r !== "string")) {
        err("refs", `node ${n.id}: refs must be string[]`, n.id);
      }
    }
    if (n.table !== void 0) {
      const t = n.table;
      if (typeof t !== "object" || t === null) {
        err("table", `node ${n.id}: table must be an object`, n.id);
      } else {
        if (t.cols !== void 0) {
          if (!Array.isArray(t.cols) || t.cols.some((c) => typeof c !== "string"))
            err("table", `node ${n.id}: table.cols must be string[]`, n.id);
          else if (t.cols.length > MAX_TABLE_COLS)
            err(
              "table",
              `node ${n.id}: table.cols max ${MAX_TABLE_COLS}, got ${t.cols.length}`,
              n.id
            );
        }
        if (t.rows !== void 0) {
          if (!Array.isArray(t.rows) || t.rows.some(
            (r) => !Array.isArray(r) || r.some((c) => typeof c !== "string")
          ))
            err("table", `node ${n.id}: table.rows must be string[][]`, n.id);
          else if (t.rows.length > MAX_TABLE_ROWS)
            err(
              "table",
              `node ${n.id}: table.rows max ${MAX_TABLE_ROWS}, got ${t.rows.length}`,
              n.id
            );
        }
        if (n.shape !== "table")
          warn(
            "table",
            `node ${n.id}: table data on a non-table node is ignored`,
            n.id
          );
      }
    }
  }
  const edgeIds = /* @__PURE__ */ new Set();
  for (const e of s.edges ?? []) {
    if (typeof e.id !== "string" || !e.id) {
      err("id", "edge without id");
      continue;
    }
    if (edgeIds.has(e.id)) err("dup-id", `duplicate id ${e.id}`, e.id);
    edgeIds.add(e.id);
    if (!seen.has(e.from))
      err("from", `edge ${e.id}: unknown from "${e.from}"`, e.id);
    if (!seen.has(e.to)) err("to", `edge ${e.id}: unknown to "${e.to}"`, e.id);
    if (!EDGE_STYLES.includes(e.style))
      err("style", `edge ${e.id}: unknown style ${JSON.stringify(e.style)}`, e.id);
    if (e.label !== void 0 && typeof e.label !== "string")
      err("label", `edge ${e.id}: label must be a string`, e.id);
    if (e.description !== void 0 && typeof e.description !== "string")
      err("desc", `edge ${e.id}: description must be a string`, e.id);
    if (e.fromSide !== void 0 && !SIDES.includes(e.fromSide))
      err(
        "side",
        `edge ${e.id}: bad fromSide ${JSON.stringify(e.fromSide)}`,
        e.id
      );
    if (e.toSide !== void 0 && !SIDES.includes(e.toSide))
      err("side", `edge ${e.id}: bad toSide ${JSON.stringify(e.toSide)}`, e.id);
  }
  const zoneIds = /* @__PURE__ */ new Set();
  for (const z of s.zones ?? []) {
    if (typeof z.id !== "string" || !z.id) {
      err("id", "zone without id");
      continue;
    }
    if (zoneIds.has(z.id)) err("dup-id", `duplicate zone id ${z.id}`, z.id);
    zoneIds.add(z.id);
    if (typeof z.label !== "string" || !z.label.trim())
      warn("label", `zone ${z.id}: empty label`, z.id);
    if (z.description !== void 0 && typeof z.description !== "string")
      err("desc", `zone ${z.id}: description must be a string`, z.id);
    if (![z.x, z.y, z.w, z.h].every(Number.isFinite))
      err("coords", `zone ${z.id}: x/y/w/h must be numbers`, z.id);
    else if (z.w <= 0 || z.h <= 0)
      err("coords", `zone ${z.id}: w/h must be positive`, z.id);
  }
  for (const n of s.nodes ?? []) {
    const linked = (s.edges ?? []).some((e) => e.from === n.id || e.to === n.id);
    if (!linked) warn("orphan", `node ${n.id} ("${n.label}") has no edges`, n.id);
  }
  return { errors, warnings };
}
function checkRefs(s, exists) {
  const out = [];
  for (const n of s.nodes ?? []) {
    for (const ref of n.refs ?? []) {
      if (!exists(ref))
        out.push({
          level: "warn",
          code: "stale-ref",
          message: `node ${n.id}: ref "${ref}" does not exist`,
          id: n.id
        });
    }
  }
  return out;
}

// core/src/ids.ts
function nextNodeId(s) {
  const taken = new Set((s.nodes ?? []).map((n2) => n2.id));
  let n = s.meta.nextId.n;
  while (taken.has(`n${n}`)) n++;
  s.meta.nextId.n = n;
  return `n${n}`;
}
function nextEdgeId(s) {
  const taken = /* @__PURE__ */ new Set([
    ...(s.edges ?? []).map((e2) => e2.id),
    ...(s.zones ?? []).map((z) => z.id)
  ]);
  let e = s.meta.nextId.e;
  while (taken.has(`e${e}`) || taken.has(`z${e}`)) e++;
  s.meta.nextId.e = e;
  return `e${e}`;
}
function consumeNodeId(s) {
  const id = nextNodeId(s);
  s.meta.nextId.n++;
  return id;
}
function consumeEdgeId(s) {
  const id = nextEdgeId(s);
  s.meta.nextId.e++;
  return id;
}
function consumeZoneId(s) {
  const id = nextEdgeId(s).replace("e", "z");
  s.meta.nextId.e++;
  return id;
}
function emptyScheme(name) {
  return {
    format: "block-llm",
    version: 1,
    rev: 0,
    name,
    project: { root: ".", codePaths: ["src/"] },
    nodes: [],
    edges: [],
    zones: [],
    meta: {
      updatedAt: (/* @__PURE__ */ new Date()).toISOString(),
      generator: "agent",
      nextId: { n: 1, e: 1 }
    }
  };
}

// core/src/layout.ts
var GRID_X = 160;
var GRID_Y = 100;
function findRoot(s) {
  const nodes = s.nodes ?? [];
  if (!nodes.length) return void 0;
  const hasIncoming = new Set((s.edges ?? []).map((e) => e.to));
  const roots = nodes.filter((n) => !hasIncoming.has(n.id));
  const pool = roots.length ? roots : nodes;
  const key = (n) => Number.parseInt(n.id.replace(/\D/g, ""), 10) || 0;
  return pool.reduce((a, b) => key(a) <= key(b) ? a : b).id;
}
function autoLayout(s) {
  const nodes = s.nodes ?? [];
  if (!nodes.length) return { placed: [] };
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const adj = /* @__PURE__ */ new Map();
  for (const n of nodes) adj.set(n.id, []);
  for (const e of s.edges ?? []) {
    if (byId.has(e.from) && byId.has(e.to)) {
      adj.get(e.from).push(e.to);
      adj.get(e.to).push(e.from);
    }
  }
  const root = findRoot(s);
  const level = /* @__PURE__ */ new Map([[root, 0]]);
  const queue = [root];
  while (queue.length) {
    const cur = queue.shift();
    for (const nb of adj.get(cur) ?? []) {
      if (!level.has(nb)) {
        level.set(nb, level.get(cur) + 1);
        queue.push(nb);
      }
    }
  }
  const sorted = [...nodes].map((n) => n.id).sort();
  let maxLevel = Math.max(0, ...level.values());
  for (const id of sorted) {
    if (!level.has(id)) level.set(id, ++maxLevel);
  }
  const occupied = new Set(
    nodes.filter((n) => Number.isFinite(n.x) && Number.isFinite(n.y)).map((n) => `${n.x}:${n.y}`)
  );
  const perLevel = /* @__PURE__ */ new Map();
  for (const id of sorted) {
    if (Number.isFinite(byId.get(id).x) && Number.isFinite(byId.get(id).y))
      continue;
    const lv = level.get(id);
    if (!perLevel.has(lv)) perLevel.set(lv, []);
    perLevel.get(lv).push(id);
  }
  const placed = [];
  const maxCount = Math.max(1, ...[...perLevel.values()].map((v) => v.length));
  const levelsSorted = [...perLevel.keys()].sort((a, b) => a - b);
  for (const lv of levelsSorted) {
    const ids = perLevel.get(lv);
    const offset = (maxCount - ids.length) * (GRID_X / 2);
    ids.forEach((id, i) => {
      let x = offset + i * GRID_X;
      const y = lv * GRID_Y;
      while (occupied.has(`${x}:${y}`)) x += GRID_X;
      occupied.add(`${x}:${y}`);
      const n = byId.get(id);
      n.x = x;
      n.y = y;
      placed.push(id);
    });
  }
  return { placed };
}

// core/src/exportMd.ts
function escMermaid(label) {
  return label.replace(/"/g, "#quot;");
}
function nodeW(n) {
  if (n.w !== void 0) return n.w;
  if (n.shape === "circle") return Math.max(80, 24 + n.label.length * 7);
  const lines = n.label.split("\n");
  if (n.shape === "table") return 260;
  return Math.max(120, 20 + Math.max(...lines.map((l) => l.length)) * 7);
}
function nodeH(n) {
  if (n.h !== void 0) return n.h;
  if (n.shape === "circle") return nodeW(n);
  if (n.shape === "table") {
    const rows = (n.table?.rows?.length ?? 0) + 1;
    return 28 + Math.min(rows, 51) * 18;
  }
  const lines = n.label.split("\n");
  return Math.max(40, lines.length * 14 + 12);
}
function nodeDecl(n) {
  const l = escMermaid(n.label).replace(/\n/g, "<br/>");
  switch (n.shape) {
    case "circle":
      return `  ${n.id}(("${l}"))`;
    case "diamond":
      return `  ${n.id}{"${l}"}`;
    default:
      return `  ${n.id}["${l}"]`;
  }
}
function exportMermaid(s) {
  const lines = ["flowchart TD"];
  const zoneOf = /* @__PURE__ */ new Map();
  for (const z of s.zones ?? []) {
    const members = (s.nodes ?? []).filter((n) => inZone(z, n.x, n.y)).map((n) => n.id);
    for (const id of members) zoneOf.set(id, z.id);
    lines.push(`  subgraph ${z.id}["${escMermaid(z.label)}"]`);
    lines.push("  direction TB");
    for (const id of members) {
      const n = (s.nodes ?? []).find((x) => x.id === id);
      lines.push("  " + nodeDecl(n).trimStart());
    }
    lines.push("  end");
  }
  for (const n of s.nodes ?? []) {
    if (!zoneOf.has(n.id)) lines.push(nodeDecl(n));
  }
  for (const e of s.edges ?? []) {
    const arrow = e.style === "dashed" ? "-.->" : "-->";
    const label = e.label ? `|"${escMermaid(e.label)}"|` : "";
    lines.push(`  ${e.from} ${arrow}${label} ${e.to}`);
  }
  return lines.join("\n");
}
function inZone(z, x, y) {
  return x >= z.x && x <= z.x + z.w && y >= z.y && y <= z.y + z.h;
}
function escTd(v) {
  return String(v ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}
function exportMd(s, issues) {
  const d = (/* @__PURE__ */ new Date()).toISOString();
  const L = [];
  L.push(`# ${s.name}`, "");
  L.push(`rev: ${s.rev} \xB7 updated: ${d} \xB7 generator: ${s.meta.generator}`, "");
  L.push("## Diagram", "", "```mermaid", exportMermaid(s), "```", "");
  L.push(
    "## Nodes",
    "",
    "| id | shape | label | refs | description |",
    "|---|---|---|---|---|"
  );
  for (const n of s.nodes ?? []) {
    L.push(
      `| ${n.id} | ${n.shape} | ${escTd(n.label)} | ${escTd((n.refs ?? []).join(", "))} | ${escTd(n.description ?? "")} |`
    );
    if (n.shape === "table" && n.table) {
      const cols = n.table.cols ?? [];
      if (cols.length)
        L.push(``, `**${n.id} columns:** ${escTd(cols.join(" \xB7 "))}`);
      for (const row of n.table.rows ?? [])
        L.push(`> ${n.id} | ${row.map((c) => escTd(c)).join(" | ")} |`);
    }
  }
  L.push(
    "",
    "## Edges",
    "",
    "| id | from | to | style | label | description |",
    "|---|---|---|---|---|---|"
  );
  for (const e of s.edges ?? []) {
    L.push(
      `| ${e.id} | ${e.from} | ${e.to} | ${e.style} | ${escTd(e.label ?? "")} | ${escTd(e.description ?? "")} |`
    );
  }
  if (s.zones?.length) {
    L.push(
      "",
      "## Zones",
      "",
      "| id | label | description | nodes |",
      "|---|---|---|---|"
    );
    for (const z of s.zones) {
      const members = (s.nodes ?? []).filter((n) => inZone(z, n.x, n.y)).map((n) => n.id).join(", ");
      L.push(
        `| ${z.id} | ${escTd(z.label)} | ${escTd(z.description ?? "")} | ${members} |`
      );
    }
  }
  L.push("", "## Sync", "");
  if (issues.warnings.length) {
    for (const w of issues.warnings) L.push(`- [${w.code}] ${w.message}`);
  } else {
    L.push("_No warnings._");
  }
  L.push("");
  return L.join("\n");
}

// core/src/diff.ts
function diffSchemes(a, b) {
  const changes = [];
  const an = new Map((a.nodes ?? []).map((n) => [n.id, n]));
  const bn = new Map((b.nodes ?? []).map((n) => [n.id, n]));
  for (const [id, n] of an)
    if (!bn.has(id)) changes.push(`- node ${id} "${n.label}"`);
  for (const [id, n] of bn) {
    if (!an.has(id)) {
      changes.push(`+ node ${id} "${n.label}"`);
      continue;
    }
    const o = an.get(id);
    for (const k of ["label", "shape", "description"]) {
      if ((o[k] ?? "") !== (n[k] ?? ""))
        changes.push(
          `~ node ${id}.${k}: ${JSON.stringify(o[k] ?? "")} -> ${JSON.stringify(n[k] ?? "")}`
        );
    }
    if (o.x !== n.x || o.y !== n.y)
      changes.push(`~ node ${id} moved to ${n.x},${n.y}`);
  }
  const ae = new Map((a.edges ?? []).map((e) => [e.id, e]));
  const be = new Map((b.edges ?? []).map((e) => [e.id, e]));
  for (const [id, e] of ae)
    if (!be.has(id)) changes.push(`- edge ${id} ${e.from}->${e.to}`);
  for (const [id, e] of be) {
    if (!ae.has(id)) {
      changes.push(
        `+ edge ${id} ${e.from}->${e.to}${e.label ? ` "${e.label}"` : ""}`
      );
      continue;
    }
    const o = ae.get(id);
    if (o.from !== e.from || o.to !== e.to)
      changes.push(`~ edge ${id}: ${o.from}->${o.to} => ${e.from}->${e.to}`);
    if (o.style !== e.style)
      changes.push(`~ edge ${id}.style: ${o.style} -> ${e.style}`);
    if ((o.label ?? "") !== (e.label ?? ""))
      changes.push(`~ edge ${id}.label: -> ${JSON.stringify(e.label ?? "")}`);
  }
  if (a.name !== b.name) changes.push(`~ name: ${a.name} -> ${b.name}`);
  return changes;
}

// core/src/saveSchema.ts
import fs from "node:fs";
import path from "node:path";
var CasError = class extends Error {
  constructor(expected, actual) {
    super(
      `scheme changed on disk (rev ${expected} \u2192 ${actual}), re-read with block.mjs get and retry`
    );
    this.expected = expected;
    this.actual = actual;
  }
  expected;
  actual;
};
var ValidationError = class extends Error {
  constructor(issues) {
    super(`validation failed: ${issues.errors.map((e) => e.message).join("; ")}`);
    this.issues = issues;
  }
  issues;
};
var DIR = ".block_llm";
var AUTOSAVE_KEEP = 50;
var BACKUP_KEEP = 20;
var JOURNAL_MAX = 5e3;
var DataError = class extends Error {
};
function readRaw(rootAbs) {
  const file = path.join(rootAbs, DIR, "scheme.json");
  let text;
  try {
    text = fs.readFileSync(file, "utf8");
  } catch (e) {
    if (e.code === "ENOENT")
      throw new DataError(`no scheme at ${file}`);
    throw new DataError(`cannot read ${file}: ${e.message}`);
  }
  try {
    return JSON.parse(text);
  } catch (e) {
    throw new DataError(`invalid JSON in ${file}: ${e.message}`);
  }
}
function rotate(dir, keep) {
  let entries = [];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true }).filter((e) => e.isFile());
  } catch {
    return;
  }
  entries.sort((a, b) => b.name.localeCompare(a.name));
  for (const e of entries.slice(keep)) {
    try {
      fs.unlinkSync(path.join(dir, e.name));
    } catch {
    }
  }
}
function appendJournal(rootAbs, entry) {
  const cache = path.join(rootAbs, DIR, "cache");
  fs.mkdirSync(cache, { recursive: true });
  const journal = path.join(cache, "journal.jsonl");
  fs.appendFileSync(journal, JSON.stringify(entry) + "\n");
  try {
    const lines = fs.readFileSync(journal, "utf8").split("\n").filter(Boolean);
    if (lines.length > JOURNAL_MAX) {
      fs.writeFileSync(journal, lines.slice(-JOURNAL_MAX).join("\n") + "\n");
    }
  } catch {
  }
}
function backup(rootAbs, scheme) {
  const backupDir = path.join(rootAbs, DIR, "cache", "backup");
  fs.mkdirSync(backupDir, { recursive: true });
  const stamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
  fs.writeFileSync(
    path.join(backupDir, `rev${scheme.rev}-${stamp}.json`),
    JSON.stringify(scheme, null, 2) + "\n"
  );
  rotate(backupDir, BACKUP_KEEP);
}
function autosave(rootAbs, scheme, force) {
  const dir = path.join(rootAbs, DIR, "cache", "autosave");
  fs.mkdirSync(dir, { recursive: true });
  try {
    const latest = fs.readdirSync(dir).sort().at(-1);
    if (latest && !force) {
      const m = latest.match(/^ts(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})/);
      if (m) {
        const prev = Date.parse(`${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}Z`);
        if (Date.now() - prev < 3e4) return;
      }
    }
  } catch {
  }
  const stamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
  fs.writeFileSync(
    path.join(dir, `ts${stamp}-rev${scheme.rev}.json`),
    JSON.stringify(scheme, null, 2) + "\n"
  );
  rotate(dir, AUTOSAVE_KEEP);
}
function saveSchema(rootAbs, next, opts = {}) {
  const file = path.join(rootAbs, DIR, "scheme.json");
  let current;
  try {
    current = readRaw(rootAbs);
  } catch {
  }
  if (current && current.rev !== next.rev)
    throw new CasError(next.rev, current.rev);
  const issues = validate(next);
  if (issues.errors.length) throw new ValidationError(issues);
  next.rev = (current?.rev ?? next.rev) + 1;
  next.meta.updatedAt = (/* @__PURE__ */ new Date()).toISOString();
  const blockDir = path.join(rootAbs, DIR);
  fs.mkdirSync(path.join(blockDir, "cache"), { recursive: true });
  if (current) backup(rootAbs, current);
  autosave(rootAbs, next, opts.autosaveForce ?? true);
  const tmp = path.join(blockDir, `.scheme.json.tmp-${process.pid}`);
  fs.writeFileSync(tmp, JSON.stringify(next, null, 2) + "\n");
  fs.renameSync(tmp, file);
  const extraFiles = opts.extraFiles?.(next) ?? {};
  const md = exportMd(next, issues);
  const mdTmp = path.join(rootAbs, "SCHEME.md.tmp-") + process.pid;
  fs.writeFileSync(mdTmp, md);
  fs.renameSync(mdTmp, path.join(rootAbs, "SCHEME.md"));
  for (const [name, content] of Object.entries(extraFiles)) {
    const target = path.join(rootAbs, name);
    const tmp2 = target + `.tmp-${process.pid}`;
    fs.writeFileSync(tmp2, content);
    fs.renameSync(tmp2, target);
  }
  if (opts.journal) {
    appendJournal(rootAbs, {
      ts: (/* @__PURE__ */ new Date()).toISOString(),
      actor: opts.journal.actor,
      op: opts.journal.op,
      rev: next.rev,
      summary: opts.journal.summary
    });
  }
  return { rev: next.rev };
}

// core/src/pathjail.ts
import path2 from "node:path";
import fs2 from "node:fs";
var PathJailError = class extends Error {
};
function jail(rootAbs, rel) {
  if (typeof rel !== "string" || !rel) throw new PathJailError("empty path");
  if (path2.isAbsolute(rel)) {
    const norm = path2.normalize(rel);
    if (!norm.startsWith(rootAbs + path2.sep) && norm !== rootAbs) {
      throw new PathJailError(`path escapes project root: ${rel}`);
    }
    return norm;
  }
  const resolved = path2.resolve(rootAbs, rel);
  const rootWithSep = rootAbs.endsWith(path2.sep) ? rootAbs : rootAbs + path2.sep;
  if (resolved !== rootAbs && !resolved.startsWith(rootWithSep)) {
    throw new PathJailError(`path escapes project root: ${rel}`);
  }
  return resolved;
}
function jailReal(rootAbs, rel) {
  const resolved = jail(rootAbs, rel);
  const rootReal = fs2.realpathSync.native(rootAbs);
  try {
    const real = fs2.realpathSync.native(resolved);
    if (real !== rootReal && !real.startsWith(rootReal + path2.sep)) {
      throw new PathJailError(`symlink escapes project root: ${rel}`);
    }
    return real;
  } catch (e) {
    if (e.code === "ENOENT") return resolved;
    if (e instanceof PathJailError) throw e;
    throw new PathJailError(`cannot resolve path: ${rel}`);
  }
}
function findProjectDir(cwd) {
  const hits = [];
  let dir = path2.resolve(cwd);
  let gitRoot = null;
  let d = dir;
  while (true) {
    if (fs2.existsSync(path2.join(d, ".git"))) {
      gitRoot = d;
      break;
    }
    const parent = path2.dirname(d);
    if (parent === d) break;
    d = parent;
  }
  while (true) {
    if (fs2.existsSync(path2.join(dir, ".block_llm", "scheme.json")))
      hits.push(dir);
    if (gitRoot && dir === gitRoot) break;
    const parent = path2.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return [...new Set(hits)];
}

// core/src/gitmd.ts
import fs3 from "node:fs";
import path3 from "node:path";
function ensureGitignoreLine(rootAbs, line) {
  const file = path3.join(rootAbs, ".gitignore");
  let text = "";
  try {
    text = fs3.readFileSync(file, "utf8");
  } catch {
  }
  const lines = text.split("\n").map((l) => l.trimEnd());
  if (lines.some((l) => l === line || l === line + "/")) return false;
  fs3.writeFileSync(
    file,
    (text && !text.endsWith("\n") ? text + "\n" : text) + line + "\n"
  );
  return true;
}
var AGENTS_START = "<!-- block-llm:start -->";
var AGENTS_END = "<!-- block-llm:end -->";
function agentsSection() {
  return [
    AGENTS_START,
    "## Project scheme",
    "",
    "This project keeps a living logic scheme in `.block_llm/`.",
    "Before architectural changes read `SCHEME.md`.",
    "After them update the scheme with the block-llm skill.",
    AGENTS_END,
    ""
  ].join("\n");
}
function ensureAgentsSection(rootAbs) {
  const file = path3.join(rootAbs, "AGENTS.md");
  let text = "";
  try {
    text = fs3.readFileSync(file, "utf8");
  } catch {
  }
  if (text.includes(AGENTS_START)) {
    const re = new RegExp(`${AGENTS_START}[\\s\\S]*?${AGENTS_END}`);
    const next = text.replace(re, agentsSection().trimEnd());
    if (next !== text) {
      fs3.writeFileSync(file, next);
      return true;
    }
    return false;
  }
  fs3.writeFileSync(
    file,
    (text ? text.trimEnd() + "\n\n" : "") + agentsSection()
  );
  return true;
}

// core/src/renderHtml.ts
var DATA_MARKER = "scheme-data";
var HtmlError = class extends Error {
};
function embedJson(s) {
  return JSON.stringify(s, null, 2).replace(/</g, "\\u003c");
}
function renderHtml(template, scheme) {
  const script = `<script type="application/json" id="${DATA_MARKER}">${embedJson(scheme)}</script>`;
  const re = new RegExp(
    `<script type="application/json" id="${DATA_MARKER}">[\\s\\S]*?</script>`
  );
  if (!re.test(template)) {
    throw new HtmlError(
      `editor template has no <script type="application/json" id="${DATA_MARKER}"> marker`
    );
  }
  return template.replace(re, () => script);
}
function extractSchemeJson(html) {
  const re = new RegExp(
    `<script type="application/json" id="${DATA_MARKER}">([\\s\\S]*?)</script>`
  );
  const m = html.match(re);
  if (!m) throw new HtmlError(`no embedded scheme data (id="${DATA_MARKER}")`);
  let parsed;
  try {
    parsed = JSON.parse(m[1]);
  } catch (e) {
    throw new HtmlError(
      `embedded scheme is not valid JSON: ${e.message}`
    );
  }
  if (!parsed || typeof parsed !== "object" || parsed.format !== "block-llm") {
    throw new HtmlError("embedded data is not a block-llm scheme");
  }
  return parsed;
}
export {
  AGENTS_END,
  AGENTS_START,
  AUTOSAVE_KEEP,
  BACKUP_KEEP,
  CasError,
  DIR,
  DataError,
  EDGE_STYLES,
  FORMAT,
  GRID_X,
  GRID_Y,
  JOURNAL_MAX,
  MAX_TABLE_COLS,
  MAX_TABLE_ROWS,
  PathJailError,
  SHAPES,
  SIDES,
  SUPPORTED_VERSION,
  ValidationError,
  agentsSection,
  autoLayout,
  checkRefs,
  consumeEdgeId,
  consumeNodeId,
  consumeZoneId,
  diffSchemes,
  emptyScheme,
  ensureAgentsSection,
  ensureGitignoreLine,
  escMermaid,
  exportMd,
  exportMermaid,
  extractSchemeJson,
  findProjectDir,
  findRoot,
  jail,
  jailReal,
  nextEdgeId,
  nextNodeId,
  nodeH,
  nodeW,
  readRaw,
  renderHtml,
  saveSchema,
  validate
};
